/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokuygulamasi;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cemr_
 */
public class Stok extends javax.swing.JFrame {

    /**
     * Creates new form Stok
     */
    public Stok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        urun = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        fiyat = new javax.swing.JLabel();
        tx_urun = new javax.swing.JTextField();
        tx_fiyat = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_table = new javax.swing.JTable();
        ekle_button = new javax.swing.JButton();
        com_kategori = new javax.swing.JComboBox<>();
        guncelle_butonu = new javax.swing.JButton();
        delete_buton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urun.setText("ürün ismi : ");

        kategori.setText("kategori : ");

        fiyat.setText("fiyat : ");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        urun_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ürün ismi", "kategori", "fiyat"
            }
        ));
        urun_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_table);

        ekle_button.setText("urun_ekle");
        ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_buttonActionPerformed(evt);
            }
        });

        com_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kultur", "edebiyat", "matematik", "turkce", "bilgisayar" }));

        guncelle_butonu.setText("urun güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });

        delete_buton.setText("urun sil");
        delete_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urun, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fiyat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tx_urun, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(tx_fiyat)
                                    .addComponent(com_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ekle_button, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(guncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_buton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_urun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_butonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_buton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_buttonActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_table.getModel();
        
        if (tx_urun.getText().trim().equals("")) {//bu trim fonksiyonu bslukları kaldırıyor
           mesaj_yazisi.setText("ürün ismi boş bırakılamaz...");
        }else{
          Object[] eklenecek = {tx_urun.getText(),com_kategori.getSelectedItem().toString(),tx_fiyat.getText()};
          model.addRow(eklenecek);
        }
    }//GEN-LAST:event_ekle_buttonActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_table.getModel();
        
        int secili_row = urun_table.getSelectedRow();
         if (secili_row == -1) {
             if (urun_table.getRowCount() == 0) {
                 mesaj_yazisi.setText("ürün tablosu suanda bos..");
             }else{
                 mesaj_yazisi.setText("lütfen güncellenecek bir ürün secin");
             }
        }else{
             model.setValueAt(tx_urun.getText(), secili_row, 0);
             model.setValueAt(com_kategori.getSelectedItem().toString(), secili_row, 1);
             model.setValueAt(tx_fiyat.getText(), secili_row, 2);
             
             mesaj_yazisi.setText("ürün basarıyla guncellendi");
         }
        
    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void urun_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) urun_table.getModel();
         int secili_row = urun_table.getSelectedRow();
         
         tx_urun.setText(model.getValueAt(secili_row, 0).toString());
         com_kategori.setSelectedItem(model.getValueAt(secili_row, 1).toString());
         tx_fiyat.setText(model.getValueAt(secili_row, 2).toString());
        
    }//GEN-LAST:event_urun_tableMouseClicked

    private void delete_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_butonActionPerformed
        // TODO add your handling code here:
         mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_table.getModel();
        
        int secili_row = urun_table.getSelectedRow();
         if (secili_row == -1) {
             if (urun_table.getRowCount() == 0) {
                 mesaj_yazisi.setText("ürün tablosu suanda bos..");
             }else{
                 mesaj_yazisi.setText("lütfen silmek istediğiniz bir ürün secin");
             }
        }else{
            model.removeRow(secili_row);
             
             mesaj_yazisi.setText("ürün basarıyla silindi");
         }
    }//GEN-LAST:event_delete_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_kategori;
    private javax.swing.JButton delete_buton;
    private javax.swing.JButton ekle_button;
    private javax.swing.JLabel fiyat;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField tx_fiyat;
    private javax.swing.JTextField tx_urun;
    private javax.swing.JLabel urun;
    private javax.swing.JTable urun_table;
    // End of variables declaration//GEN-END:variables
}
